### ISSUE TITLE
Routes are not working properly

### ISSUE THREAD

**Issue by ashwaniYDV** [Njack-IITP/njack-web-react#19]
## Steps to reproduce:
1) Go to team page
2) open any facebook profile of any coord
3) come back to team page

**Comment by aradhya-gupta** [comment]
The issue was due to surge. When deployed on surge, the application being a single paged application only has its main route deployed on surge and all other routes are accessible from within the app and not outside of it. When pressing back the request goes to "njack-react-website.surge.sh/team" but no such page exists on surge. Surge only has the domain "njack-react-website.surge.sh" which stores the entire website.

As a fix of the issue I have used target=_blank for the social media links. Now the links open in a new tab so no need to press the back button.
